### ISSUE TITLE
AFTER CLONE

### ISSUE THREAD

**Issue by waseem-terafort** [SimonScholz/qr-code-with-logo#14]
after clone i got like this .... i try rebuild again and gradle sync too

![image](https://github.com/SimonScholz/qr-code-with-logo/assets/129371314/48d01dc1-ca8d-4213-9fbe-7fe13006d588)

**Comment by SimonScholz** [comment]
Hi @waseem-terafort 

The `local.properties` file is **not** part of my repository.
It seems that you're using Android Studio, which for whatever reason auto-generated this file.

Can you share some more details why you cloned the Repo, so that I can give you some guidance?

If you just want to use the qr-code library you can simply obtain it from maven central, which is also outlined in the Quick Start section of my README.

And what is actually not working for you?
In my opinion you can simply delete the `local.properties` file, since no android is needed here.
